#!/bin/sh
# A simple runner file to covid code
# Eduardo M. Morais - 2020/07/10

#read -s -p "Username: " user
read -p "Commit message: " commit_msg

echo "$commit_msg"
#read -p "Password: " password
# rm -rf build
# rm -rf  dist
# rm -rf cov19.egg-info

# python setup.py sdist bdist_wheel
# twine upload dist/*

git status
git add .
git commit -m "$commit_msg"