#!/bin/sh
# A simple runner file to covid code
# Eduardo M. Morais - 2020/07/10

file=$1
ext=".ini"
file_ini=$file$ext

# create a directory
cd results
#mkdir -p $file
#cd ..

if [ -e $arq ]
then
echo ""
else
echo "Creting directory results/$file."
mkdir -p $file
fi

cd ..


file="parameters/$file_ini"
python -m cov19 $file
